config/routes.rb
Rails.application.routes.draw do
  root to: 'games#new'

  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
  get 'reset', to: 'games#reset'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def new
    @letters = []
    10.times { @letters << ('A'..'Z').to_a.sample }
  end

  def score
    @api_url = "https://wagon-dictionary.herokuapp.com/#{params[:word]}"
    @word_json = JSON.parse(open(@api_url).read)
    @result = { word: params[:word], grid: params[:grid] }

    if !in_grid?(params[:word], params[:grid])
      @result[:result] = 1
    elsif !@word_json['found']
      @result[:result] = 2
    else
      @result[:result] = 3
    end
    @result[:round_score] = calc_score(@result[:result], params[:word])
    session[:score] += calc_score(@result[:result], params[:word])
  end

  def reset
    session[:score] = 0
    redirect_to new_path
  end

  def in_grid?(word, grid)
    grid_array = grid.split(' ')
    word.split('').each do |letter|
      return false unless grid_array.include?(letter.upcase)

      grid_array.slice!(grid_array.index(letter.upcase))
    end
    true
  end

  def calc_score(result, word)
    return 0 if [1, 2].include?(result)

    word.length
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="container">
  <h1>New Game !</h1>
  <div class="letters">
    <% @letters.each do |letter| %>
      <div class="letter">
         <h2><%= "#{letter}" %></h2>
      </div>
    <% end %>
  </div>
  <div class="user-form">
    <form action="/score" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <%= hidden_field_tag :grid, @letters %>
      <label for="">What is the longest word you can find?</label>
      <div class="form-group">
        <input type="text" name="word" class="input-word">
        <input type="submit" value="Play" class="input-submit">
      </div>
    </form>
  </div >
  <p>Your total score is <%= "#{session[:score]}" %></p>
</div>

app/views/games/score.html.erb
<div class="container">
  <h1>Results</h1>
  <% case @result[:result] when 1 %>
    <% @grid_letters = @result[:grid].split(' ').join(', ') %>
    <p>Sorry but <b><%= "#{@result[:word].upcase}" %></b> can not be made from <%= "#{@grid_letters}" %></p>
    <% when 2 %>
    <p>Sorry but <b><%= "#{@result[:word].upcase}" %></b> is not an english word...</p>
    <% when 3 %>
    <p>Nice!</p>
  <% end %>
  <p></p>
  <p>Your total score is <%= "#{session[:score]}" %></p>
  <%= link_to 'Play again', new_path  %>
  <%= link_to 'Reset score', reset_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>